// Chaotic announcement templates, in the spirit of the mascot NAMES list.
//
// Every Discord announcement = one random INTRO (mascot-signed) + one random
// body line for the event type. ~30 of each × 30 intros ≈ 900+ distinct
// messages per type. Add more lines to any array freely - `npm test` checks
// that every template's placeholders resolve.
//
// Placeholders:
//   {mascot}                              - today's mascot name
//   milestone: {player} {total} {flavor} {bonus}
//   streak:    {player} {days} {bonus}
//   roulette:  {player} {prize} {amount}   ({amount} is signed, e.g. "+7")
//   sweep:     {players} {count} {bonus}   ({players} already bold + joined)
//   recap:     {topPlayer} {topPoints} {playerCount} {gameCount}

const INTROS = [
  '🎲 **{mascot}** has entered the chat 🎲',
  '🎲 **{mascot}** kicks the door off its hinges 🎲',
  '📣 a wild **{mascot}** appears',
  '🎲 **{mascot}** stumbles in, uninvited 🎲',
  '🚨 **{mascot}** is here and has opinions',
  '🎪 ladies and gentlemen, **{mascot}**',
  '🎲 **{mascot}** has crawled out of the vents 🎲',
  '📯 hear ye, hear ye — **{mascot}** speaks',
  '🌊 something surfaces. it is **{mascot}**.',
  '🎲 **{mascot}** clocks in for bonus duty 🎲',
  '⚡ **{mascot}** has been released from its enclosure',
  '🎲 by the power vested in **{mascot}** 🎲',
  '🫧 **{mascot}** bubbles up from the deep',
  '🎲 **{mascot}** would like a word 🎲',
  '📢 incoming transmission from **{mascot}**',
  '🎲 **{mascot}** is legally required to announce the following 🎲',
  '🥁 drumroll, please, for **{mascot}**',
  '🎲 **{mascot}** materializes, smelling faintly of pennies 🎲',
  '👀 **{mascot}** has been watching. **{mascot}** has notes.',
  '🎲 **{mascot}** interrupts your regularly scheduled programming 🎲',
  "🎲 it's **{mascot}** o'clock 🎲",
  '🔔 **{mascot}** rings the bonus bell',
  '🎲 **{mascot}** rises from the sea foam like a discount Venus 🎲',
  "📬 **{mascot}** has mail for you. it's points.",
  '🎲 **{mascot}** did not ask to be here either 🎲',
  '🎺 a fanfare, poorly played, for **{mascot}**',
  '🎲 **{mascot}** slaps a fresh sticker on the leaderboard 🎲',
  "🧾 **{mascot}** presents today's ledger",
  '🎲 **{mascot}** is contractually obligated to say this 🎲',
  '🌀 reality warps slightly. **{mascot}** steps through.',
  '🎲 **{mascot}** has kicked in the skylight 🎲',
  '📸 **{mascot}** would like everyone to look natural',
];

const MILESTONE = [
  '🎯 **{player}** just landed dead-on **{total}** — {flavor} +{bonus} points, no take-backs.',
  '📈 **{player}** hit **{total}** total. {flavor} the universe grants +{bonus}.',
  '🏅 **{total}** points, exactly, for **{player}**. {flavor} enjoy the +{bonus}.',
  "**{player}** rolled up to **{total}** on the nose. {flavor} +{bonus}, chef's kiss.",
  'somebody get **{player}** a plaque — **{total}** total. {flavor} +{bonus}.',
  '**{player}** has achieved the sacred number **{total}**. {flavor} +{bonus} tribute.',
  'alert: **{player}** is now sitting pretty on **{total}**. {flavor} +{bonus}.',
  '**{player}** parked it perfectly at **{total}**. {flavor} take +{bonus} and go.',
  'the odometer clicked to **{total}** for **{player}**. {flavor} +{bonus}.',
  '**{player}** threaded the needle at **{total}**. {flavor} +{bonus} for the craftsmanship.',
  'witnessed: **{player}** at **{total}** exactly. {flavor} +{bonus} hush money.',
  '**{player}** hit **{total}** and the room went quiet. {flavor} +{bonus}.',
  "**{total}**. **{player}**. {flavor} +{bonus}, don't spend it all in one place.",
  '**{player}** stuck the landing on **{total}**. {flavor} +{bonus} from the judges.',
  'breaking: **{player}** reaches **{total}**. {flavor} +{bonus} awarded, begrudgingly.',
  '**{player}** just tapped **{total}** like a bus stop. {flavor} +{bonus}.',
  'the prophecy said **{total}**. **{player}** fulfilled it. {flavor} +{bonus}.',
  '**{player}** is now precisely **{total}** points of person. {flavor} +{bonus}.',
  'ding! **{player}** at **{total}**. {flavor} collect your +{bonus}.',
  '**{player}** hit **{total}** and I felt that. {flavor} +{bonus}.',
  'for landing exactly on **{total}**, **{player}** receives +{bonus} and my respect. {flavor}',
  '**{player}** = **{total}** now. {flavor} the +{bonus} is non-negotiable.',
  'mark the calendar: **{player}** touched **{total}**. {flavor} +{bonus}.',
  '**{player}** rolled a natural **{total}**. {flavor} +{bonus} loot.',
  '**{total}** total points for **{player}**, not a decimal more. {flavor} +{bonus}.',
  '**{player}** has been assigned the number **{total}**. {flavor} +{bonus} severance.',
  'it had to be **{player}**, and it had to be **{total}**. {flavor} +{bonus}.',
  '**{player}** speedran to exactly **{total}**. {flavor} +{bonus}, any%.',
  'the leaderboard shivers: **{player}** at **{total}**. {flavor} +{bonus}.',
  '**{player}** achieved perfect alignment at **{total}**. {flavor} +{bonus} cosmic reward.',
  '**{player}** knocked on **{total}** and it answered. {flavor} +{bonus}.',
];

const STREAK = [
  "🔥 **{player}** has shown up **{days}** days straight. that's a lifestyle now. +{bonus}.",
  '**{player}** is on a **{days}**-day streak and cannot be stopped, only contained. +{bonus}.',
  '**{days}** consecutive days of **{player}** refusing to skip. +{bonus} for the obsession.',
  'streak check: **{player}**, **{days}** days. touch grass (afterward). +{bonus}.',
  "**{player}** hasn't missed in **{days}** days. the games fear them. +{bonus}.",
  '**{days}** days, no gaps, all **{player}**. +{bonus} and a small trophy made of lint.',
  '**{player}** logged in **{days}** days running. discipline! or something like it. +{bonus}.',
  "the **{player}** streak reaches **{days}**. we're all a little scared. +{bonus}.",
  '**{days}**-day streak unlocked by **{player}**. +{bonus}. please hydrate.',
  '**{player}** has played every one of the last **{days}** days. +{bonus} for the bit.',
  'nobody tell **{player}** they can stop — **{days}** days, +{bonus}.',
  '**{player}** is **{days}** days deep. no notes. +{bonus}.',
  'consistency award goes to **{player}**: **{days}** days. +{bonus} and our concern.',
  '**{days}** days in a row?? **{player}**?? incredible. worrying. +{bonus}.',
  '**{player}** has a **{days}**-day streak and a look in their eye. +{bonus}.',
  'the calendar has been fully colonized by **{player}** — **{days}** days. +{bonus}.',
  '**{player}** shows up like the tide: **{days}** days and counting. +{bonus}.',
  '**{days}** for **{player}**. the streak is now load-bearing. +{bonus}.',
  '**{player}** cleared **{days}** straight days. +{bonus}. impressive. worrying. both.',
  'streak of **{days}** for **{player}**. +{bonus} and a firm handshake.',
  "**{player}** just won't quit — **{days}** days, +{bonus}.",
  '**{days}** consecutive appearances by **{player}**. +{bonus} appearance fee.',
  '**{player}** is speedrunning "never miss a day." **{days}** in. +{bonus}.',
  'the **{days}**-day club has one member and it is **{player}**. +{bonus} dues refund.',
  '**{player}**: **{days}** days. the streak has its own gravity now. +{bonus}.',
  '**{days}** days without a single skip, courtesy of **{player}**. +{bonus}.',
  '**{player}** has attended **{days}** days in a row. attendance prize: +{bonus}.',
  'logging **{days}** straight, **{player}** achieves minor legend status. +{bonus}.',
  '**{player}** kept the flame lit for **{days}** days. +{bonus} kindling.',
  '**{days}**-day heater from **{player}**. +{bonus}. do not approach.',
];

const ROULETTE = [
  '🎰 **{player}** had the worst day, spun the wheel, got {prize} ({amount}).',
  'the wheel pitied **{player}** and coughed up {prize} ({amount}).',
  "**{player}** finished last and the prize goblin handed them {prize} ({amount}).",
  'rock bottom has perks: **{player}** spun {prize} ({amount}).',
  '**{player}** ate dirt today, so the wheel gave them {prize} ({amount}).',
  'consolation from the void for **{player}**: {prize} ({amount}).',
  "**{player}** drew {prize} from the loser's tombola ({amount}).",
  'the mercy wheel turns for **{player}**: {prize} ({amount}).',
  "**{player}** was in the basement, so here's {prize} ({amount}).",
  'for services to coming last, **{player}** receives {prize} ({amount}).',
  '**{player}** spun the wheel of "at least you showed up" and won {prize} ({amount}).',
  'pity applause for **{player}**, plus {prize} ({amount}).',
  '**{player}** hit the bottom of the barrel and found {prize} ({amount}).',
  "the wheel looked at **{player}**'s day and sighed, then produced {prize} ({amount}).",
  '**{player}** gets the underdog bag: {prize} ({amount}).',
  'last place, first dibs on the wheel — **{player}** grabbed {prize} ({amount}).',
  '**{player}** spun {prize} ({amount}). the comeback starts... probably not today.',
  'karma rebate for **{player}**: {prize} ({amount}).',
  '**{player}** was today’s designated disaster, so: {prize} ({amount}).',
  'the leaderboard felt bad for **{player}** and expensed {prize} ({amount}).',
  '**{player}** reached in blind and pulled {prize} ({amount}).',
  'wheel says **{player}** gets {prize} ({amount}). wheel does not explain itself.',
  '**{player}** cashed in their last-place ticket for {prize} ({amount}).',
  'a soft landing for **{player}**: {prize} ({amount}).',
  '**{player}** spun and the machine went {prize} ({amount}). nobody knows how it works.',
  '**{player}** got dragged, then got {prize} ({amount}).',
  'the rubber band snaps back for **{player}**: {prize} ({amount}).',
  '**{player}** loses the day, wins {prize} ({amount}). balance.',
  'for **{player}**, the wheel produced {prize} ({amount}) and a faint whirring sound.',
  '**{player}** spun {prize} ({amount}). the deep sea provides.',
];

// appended to a roulette line when the day's single worst player spins twice
const DOUBLE_SPIN = [
  ' — and again, because dead last spins twice',
  ' ×2, since somebody had to be the absolute worst',
  ' (two spins for the day’s biggest disaster)',
  ' — double dip, last-place privileges',
  ' ×2 for finishing last of the last',
  ' (the wheel span twice; they earned that)',
  ' — bonus spin for spectacular failure',
  ' ×2. rock bottom comes with a punch card.',
];

const SWEEP = [
  '✅ full sweep, all {count} games: {players}. +{bonus} each for having no life today.',
  '🧹 {players} played everything ({count} games). +{bonus} apiece.',
  '{players} did the whole slate, {count} for {count}. +{bonus} each.',
  'completionists assemble: {players}. +{bonus} for the full {count}.',
  '{players} left no game unplayed today. +{bonus} each.',
  '100% clear by {players} — all {count} games. +{bonus}.',
  '{players} ran the table ({count} games). +{bonus} each, you maniacs.',
  'nothing skipped by {players}. +{bonus} for the perfect attendance.',
  "{players} touched every game today. wash your hands. +{bonus} each.",
  'the full {count}-game sweep goes to {players}. +{bonus}.',
  '{players} said "yes" to all {count} games. +{bonus} each.',
  'grand slam by {players}. +{bonus} apiece for the {count}-game clean sweep.',
  "{players} cleared the board. +{bonus} each. touch something that isn't a screen.",
  'every game, every one of them: {players}. +{bonus}.',
  '{players} went {count} for {count}. +{bonus} each. terrifying commitment.',
  'sweep club today: {players}. dues paid in full. +{bonus}.',
  '{players} did all {count}. the games are exhausted. +{bonus} each.',
  'full house for {players} — {count}/{count}. +{bonus}.',
  '{players} played the entire menu. +{bonus} each, tip included.',
  'no crumbs left by {players}. all {count} games. +{bonus}.',
  "{players} pulled off the full sweep. +{bonus}. we're impressed, and a little mad.",
  '{count}-for-{count} today: {players}. +{bonus} each.',
  '{players} refused to skip a single game. +{bonus} for the stubbornness.',
  'clean sweep, no notes: {players}. +{bonus} each.',
  "{players} completed today's entire circuit. +{bonus}. hydrate, legends.",
];

// End-of-day recap, sent once at the 20:00 close after everything else
// (skill points + all of today's bonuses) has settled - the day's actual
// final word, not just a bonus-by-bonus rundown.
const RECAP = [
  "📊 that's a wrap on today: **{playerCount}** players, **{gameCount}** games counted. **{topPlayer}** took the day with **{topPoints}**.",
  "🔒 today's locked in — **{topPlayer}** leads the pack with **{topPoints}** points out of **{playerCount}** players across **{gameCount}** games.",
  "the day is closed, the books are cooked: **{topPlayer}** on top with **{topPoints}**. **{playerCount}** showed up for **{gameCount}** games.",
  "final tally: **{topPlayer}** wins the day, **{topPoints}** points. **{playerCount}** players, **{gameCount}** games, no refunds.",
  "🌙 lights out on today. **{topPlayer}** takes it with **{topPoints}**. **{gameCount}** games, **{playerCount}** competitors, one champion.",
  "the sea has spoken: **{topPlayer}**, **{topPoints}** points, best of **{playerCount}** across **{gameCount}** games today.",
  "today's verdict is in — **{topPlayer}** on top with **{topPoints}**. everyone else, there's always tomorrow. (**{playerCount}** players, **{gameCount}** games.)",
  "closing the ledger: **{topPlayer}** leads today at **{topPoints}** points, out of **{playerCount}** players in **{gameCount}** games.",
  "🧾 receipt for today: **{playerCount}** players, **{gameCount}** games, and **{topPlayer}** walking away with **{topPoints}** points.",
  "the votes are counted and it wasn't close: **{topPlayer}**, **{topPoints}** points, top of **{playerCount}**.",
  "today's champion is **{topPlayer}** with **{topPoints}** points. **{gameCount}** games got counted, **{playerCount}** people showed up.",
  "and that's today, folks — **{topPlayer}** finishes on **{topPoints}**, best of **{playerCount}** across **{gameCount}** games.",
  "the sun sets on another day of this. **{topPlayer}** wins it with **{topPoints}**. (**{playerCount}** players, **{gameCount}** games.)",
  "🏆 top of today's heap: **{topPlayer}**, **{topPoints}** points. **{playerCount}** players fought over **{gameCount}** games for the privilege of losing to them.",
  "today, summarized: **{playerCount}** players, **{gameCount}** games, and **{topPlayer}** standing on top with **{topPoints}**.",
  "the day's final boss was **{topPlayer}**, clearing it with **{topPoints}** points across **{gameCount}** games and **{playerCount}** challengers.",
  "case closed on today: **{topPlayer}** leads with **{topPoints}**, ahead of **{playerCount}** players over **{gameCount}** games.",
  "today's high-water mark belongs to **{topPlayer}** — **{topPoints}** points, **{playerCount}** players, **{gameCount}** games in the books.",
  "the numbers are in and they're brutal for everyone except **{topPlayer}**, who takes today with **{topPoints}** points.",
  "🎬 that's a wrap: **{topPlayer}** stars in today's episode with **{topPoints}** points. **{playerCount}** players, **{gameCount}** games, credits roll.",
  "🐚 today's clamshell goes to **{topPlayer}** with **{topPoints}** points, out of **{playerCount}** across **{gameCount}** games.",
  "final whistle: **{topPlayer}** on **{topPoints}**, best of **{playerCount}** players over **{gameCount}** games today.",
  "the tide goes out and leaves **{topPlayer}** standing tallest at **{topPoints}** points.",
  "today's dispatch: **{playerCount}** players, **{gameCount}** games, **{topPlayer}** on top with **{topPoints}**.",
  "curtain call for today — **{topPlayer}** takes the bow with **{topPoints}** points.",
  "the box score is in: **{topPlayer}**, **{topPoints}** points, best of **{playerCount}** for the day.",
  "today's bulletin: **{topPlayer}** leads at **{topPoints}**, **{gameCount}** games counted, **{playerCount}** in the field.",
  "somebody had to win today and it was **{topPlayer}**, with **{topPoints}** points to show for it.",
  "the reckoning has arrived: **{topPlayer}** tops today's **{playerCount}** with **{topPoints}** points.",
  "🦑 ink cleared, results in: **{topPlayer}** wins the day with **{topPoints}**, out of **{playerCount}** players.",
  "the day's roundup: **{gameCount}** games, **{playerCount}** players, and **{topPlayer}** on top with **{topPoints}**.",
  "today concludes with **{topPlayer}** in first, **{topPoints}** points, ahead of **{playerCount}** others.",
  "the scoreboard has spoken, and it said **{topPlayer}**, **{topPoints}** points.",
  "nightfall report: **{topPlayer}** finishes atop **{playerCount}** players with **{topPoints}** points.",
  "today's crown goes to **{topPlayer}** — **{topPoints}** points across **{gameCount}** games.",
  "the deep sea has ranked you all, and **{topPlayer}** floats to the top with **{topPoints}**.",
  "today's final standings, briefly: **{topPlayer}** first with **{topPoints}**, **{playerCount}** total players.",
  "🎣 hook, line, and today's win goes to **{topPlayer}** with **{topPoints}** points.",
  "the gavel comes down: **{topPlayer}** wins today with **{topPoints}** points, **{gameCount}** games on the docket.",
  "today, in one sentence: **{topPlayer}** led **{playerCount}** players with **{topPoints}** points across **{gameCount}** games.",
  "closing bell for today — **{topPlayer}** rings it in at **{topPoints}** points.",
  "the results are final and unappealable: **{topPlayer}**, **{topPoints}** points, top of **{playerCount}**.",
  "today's headline: '**{topPlayer}** wins with **{topPoints}** points,' more at 11.",
  "the sun has set on **{gameCount}** games and **{playerCount}** players; **{topPlayer}** stands tallest at **{topPoints}**.",
  "one for the record books: **{topPlayer}**, **{topPoints}** points, today's best of **{playerCount}**.",
  "the final buzzer sounds and **{topPlayer}** is on top with **{topPoints}** points.",
  "🌊 the wave crests and **{topPlayer}** rides it to **{topPoints}** points, best of **{playerCount}**.",
  "today's postmortem: **{playerCount}** players, **{gameCount}** games, one clear winner — **{topPlayer}** with **{topPoints}**.",
  "the day is officially in the books, cover to cover: **{topPlayer}** wins with **{topPoints}** points.",
  "somebody call it: **{topPlayer}** takes today, **{topPoints}** points, **{playerCount}** players in the mix.",
  "today's MVP: **{topPlayer}**, **{topPoints}** points, out of **{gameCount}** games played by **{playerCount}** people.",
  "the numbers don't lie: **{topPlayer}** on **{topPoints}**, best of the day.",
  "and just like that, today's done — **{topPlayer}** leads with **{topPoints}** points.",
  "the final scroll unfurls: **{topPlayer}**, **{topPoints}** points, champion of today's **{playerCount}**.",
  "📯 hear this: **{topPlayer}** finishes today on **{topPoints}** points, ahead of **{playerCount}** others.",
  "the day's last word belongs to **{topPlayer}**: **{topPoints}** points, **{gameCount}** games counted.",
  "consider this today's obituary: **{playerCount}** players tried, **{topPlayer}** succeeded, **{topPoints}** points.",
  "the ink has dried on today's results: **{topPlayer}** on top with **{topPoints}** points.",
  "today, distilled: one winner (**{topPlayer}**, **{topPoints}** points), **{playerCount}** players, **{gameCount}** games.",
  "🐙 the kraken has tallied the votes: **{topPlayer}** wins with **{topPoints}** points.",
  "the final gavel: **{topPlayer}**, **{topPoints}** points, best of **{playerCount}** across **{gameCount}** games today.",
  "today's chapter closes with **{topPlayer}** on top, **{topPoints}** points to their name.",
  "the day has been weighed, measured, and won by **{topPlayer}** with **{topPoints}** points.",
  "last call on today's results: **{topPlayer}** leads with **{topPoints}**, **{playerCount}** players total.",
  "today's final standing, no appeals: **{topPlayer}** first, **{topPoints}** points.",
  "the sea has settled and **{topPlayer}** is left holding **{topPoints}** points, tops for the day.",
  "the day's ledger balances in favor of **{topPlayer}**: **{topPoints}** points.",
  "here lies today, survived by **{playerCount}** players and won by **{topPlayer}** with **{topPoints}** points.",
  "🎯 bullseye of the day goes to **{topPlayer}**, **{topPoints}** points across **{gameCount}** games.",
  "today's final transmission: **{topPlayer}** wins, **{topPoints}** points, signing off.",
  "the votes are tallied, the day is done: **{topPlayer}** on top with **{topPoints}** points.",
  "today's epilogue: **{topPlayer}**, **{topPoints}** points, out ahead of **{playerCount}** players.",
  "the day's finish line was crossed first by **{topPlayer}**, **{topPoints}** points.",
  "so ends today's saga, with **{topPlayer}** crowned at **{topPoints}** points.",
  "the day's trophy, such as it is, goes to **{topPlayer}** — **{topPoints}** points.",
  "today's parting shot: **{topPlayer}** finishes first with **{topPoints}** points, **{gameCount}** games counted.",
  "the results have been notarized: **{topPlayer}**, **{topPoints}** points, best of today.",
  "today's final score is in the mail, and it says **{topPlayer}**, **{topPoints}** points.",
  "the day wraps with **{topPlayer}** on top of **{playerCount}** players, **{topPoints}** points.",
  "🦀 the crab has scuttled off with today's win: **{topPlayer}**, **{topPoints}** points.",
  "today's summary, unabridged: **{topPlayer}** won with **{topPoints}** points.",
  "the day's final act belongs to **{topPlayer}**, taking **{topPoints}** points.",
  "today's numbers are locked, and **{topPlayer}** owns the top with **{topPoints}** points.",
  "the last light of today falls on **{topPlayer}**, **{topPoints}** points strong.",
  "today's closing argument: **{topPlayer}**, **{topPoints}** points, rests its case.",
  "the day has been adjudicated in favor of **{topPlayer}**, **{topPoints}** points.",
  "today's final frame: **{topPlayer}** on top with **{topPoints}** points, **{playerCount}** players total.",
  "the sun sets on **{playerCount}** hopefuls; **{topPlayer}** remains standing at **{topPoints}** points.",
  "today's last laugh belongs to **{topPlayer}**, **{topPoints}** points and counting.",
  "the day's final receipt: **{topPlayer}**, **{topPoints}** points, thank you for playing.",
  "🫧 the bubbles have cleared and **{topPlayer}** is visible on top with **{topPoints}** points.",
  "today's postgame: **{topPlayer}** takes MVP honors with **{topPoints}** points.",
  "the day's final tally has been notarized, stamped, and awarded to **{topPlayer}** — **{topPoints}** points.",
  "today, in closing: **{topPlayer}** wins with **{topPoints}** points out of **{playerCount}** players.",
  "the last word on today goes to **{topPlayer}**, **{topPoints}** points and no complaints filed.",
  "today's finale: **{topPlayer}** takes the crown, **{topPoints}** points, **{gameCount}** games in the books.",
  "the day is signed, sealed, and delivered to **{topPlayer}** — **{topPoints}** points.",
  "today's last stand was won by **{topPlayer}**, **{topPoints}** points, **{playerCount}** players fought for it.",
  "the curtain falls on today with **{topPlayer}** in the spotlight, **{topPoints}** points.",
  "and that's a full stop on today — **{topPlayer}** finishes first with **{topPoints}** points.",
];

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function fill(tpl, vars) {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : `{${k}}`));
}

// one random intro + one random body, filled
function compose(bodies, vars) {
  return `${fill(pick(INTROS), vars)}\n${fill(pick(bodies), vars)}`;
}

const say = {
  milestone: (vars) => compose(MILESTONE, vars),
  streak: (vars) => compose(STREAK, vars),
  intro: (vars) => fill(pick(INTROS), vars),
  sweepLine: (vars) => fill(pick(SWEEP), vars),
  rouletteLine: (vars, twice) =>
    fill(pick(ROULETTE), vars) + (twice ? pick(DOUBLE_SPIN) : ''),
  recap: (vars) => compose(RECAP, vars),
};

module.exports = { say, fill, pick, INTROS, MILESTONE, STREAK, ROULETTE, SWEEP, DOUBLE_SPIN, RECAP };
